### ISSUE TITLE
Won't import CitrinationClient

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/python-citrination-client#6]
```
[maxhutch@helm ~]$ ~/anaconda3/bin/pip install citrination-client
Collecting citrination-client
  Downloading citrination-client-1.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in ./anaconda3/lib/python3.5/site-packages (from citrination-client)
Building wheels for collected packages: citrination-client
  Running setup.py bdist_wheel for citrination-client ... done
  Stored in directory: /home/maxhutch/.cache/pip/wheels/43/26/ff/15d30af513de93aa48dffc5fb0ecb210ae5895b7cd7c57a3ac
Successfully built citrination-client
Installing collected packages: citrination-client
Successfully installed citrination-client-1.1.0
[maxhutch@helm ~]$ ~/anaconda3/bin/ipython 
WARNING: Readline services not available or not loaded.
WARNING: The auto-indent feature requires the readline library
Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from citrination_client import CitrinationClient
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3e7f672093c6> in <module>()
----> 1 from citrination_client import CitrinationClient

/home/maxhutch/anaconda3/lib/python3.5/site-packages/citrination_client/__init__.py in <module>()
----> 1 from citrination_client import CitrinationClient

ImportError: cannot import name 'CitrinationClient'

```

**Comment by maxhutch** [comment]
Works in python2.7.  Do we only support python2.*?

**Comment by kjaym** [comment]
Two things... 

1. It's only been tested against python2, not python3. 
2. `pip install citrination-client` is going to install a version that is for new sites. If you want to interact with the current citrination.com site, follow this https://github.com/CitrineInformatics/python-citrination-client#legacy-information
